# Generated by Django 4.2.4 on 2023-10-08 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='term',
            name='boardName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planner.board'),
        ),
    ]
