# Generated by Django 4.2.4 on 2023-10-25 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_board_term_boardname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='boardName',
            new_name='board',
        ),
    ]
