version: "2.13"
services: 
  backend: 
    build: ./backend
    container_name: backend_c
    ports: 
      - '8080:8080'
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true